### ISSUE TITLE
Adding a gallery to new records

### ISSUE THREAD

**Issue by MeFuMo** [zxbodya/yii2-gallery-manager#23]
The extension works great. I haven't had a deep look into the code, but how hard would it be to change some code around so images can be added to new records in this behavior and your image attachment one? Maybe AFTER_CREATE or AFTER_UPDATE events could be tuned up for this?

Thanks!

**Comment by zxbodya** [comment]
There is no easy way to achieve this. But it is possible.

Problem is that widget needs something to attach images to(it uploads images immediately when you select them, and this is a problem since you need to save images somehow before saving form itself), so for now it requires record in db with primary key. Generally speaking it is not form widget, it is completely separate form model saving and updating.

There is two hacky solutions, you can try:

1. Create temporary record in db, before displaying widget first time
2. Automatically generate "temporary id"(for example something like "tmp<timestamp>") when displaying widget for new record, save it somewhere(session, or better hidden input in form), and move gallery files to new location using it when saving gallery.

First one is simpler for particular case, second is more complicated - but it is more general. Both are not quite clear, and will require cron job to remove "not saved" galleries.

But better, if you can - just do not do it:
 - in create form - show notice that gallery would be edited at next step
 - after creating new record - redirect to editing with anchor to gallery widget

**Comment by MeFuMo** [comment]
I see. I'd rather not hack around too much. 

I thought about a simple way to fix this via a simple interface design, more or less, without messing around with temporary ids and cron jobs. Just separating the actual forms for the fields in the model and the image attachments and gallery in, for example, two tabs (basically divs hidden via js in the same view) like "content" and "images". 

Once you save the primary model, the "images" tab becomes active, so you can actually use the behavior for the already existing model. Until then, the tab is not accesible, and a simple check for isNewRecord() or something like that in the form should be enough to prevent showing the gallery form fields if someone tries to fool around the system.

Thanks for the help. Much appreciated :)
