### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by Asetss** [zxbodya/yii2-gallery-manager#3]
error in the example where  Yii :: getAlias ('@ contentRoot')

**Comment by zxbodya** [comment]
It is just example, you can replace it with any path where you want to save your images -  as an option you can just replace it with `@webroot` (and be sure that web service has write permissions for `images` folder in webroot, or permission to create it)

---

About `contentRoot` alias - this is alias for folder with content related files(images, uploads, etc...)
And since it is shared between backend and frontend apps - it is not in one of web roots.

I have alias for it in bootstrap.php file `Yii::setAlias('contentRoot', dirname(dirname(__DIR__)) . '/contentRoot');` and appropriate aliases on my web server like this `location /uploads/ { root /work/contentRoot;}`

**Comment by zxbodya** [comment]
updated example
