### ISSUE TITLE
Главное изображение

### ISSUE THREAD

**Issue by smartbit45** [zxbodya/yii2-gallery-manager#86]
Здравствуйте! Я в yii2 совсем новичок, это по сути первый пакет, который подключил к проекту :-) В принципе все работает, но хотелось бы посоветоваться: хочу сделать в массиве изображений - одно главное, миниатюра которого, будет отображаться в списке статей (к примеру). Вот что в голову пришло: 1)создать в таблице поле isMain, 2)с виджетом придется поковыряться, ума не приложу как эту кнопку туда прилепить, 3)создать метод для получения этой картинки из базы ( только для меня пока не очевидно где его реализовывать, но почему то кажется что не в самой модели статьи). В общем буду признателен за Ваши комментарии.

**Comment by zxbodya** [comment]
I think it is better to have the main image separate from a gallery. 

For use-cases like this, I did a separate extension allowing to attach single image to the model: https://github.com/zxbodya/yii2-image-attachment

this allows having a different configuration for the image, which is helpful because the cover is usually used in a different context

**Comment by smartbit45** [comment]
> I think it is better to have the main image separate from a gallery.
> 
> For use-cases like this, I did a separate extension allowing to attach single image to the model: https://github.com/zxbodya/yii2-image-attachment
> 
> this allows having a different configuration for the image, which is helpful because the cover is usually used in a different context

Thank you very much!
